### ISSUE TITLE
no song.

### ISSUE THREAD

**Issue by davut5** [abingeorgev/Sing-and-Record#1]
i run it from ios simulator. No song in list.

**Comment by abingeorgev** [comment]
Hi davut, I have done it like offline. You can add a karaoke via itunes to your mobile and load it in the app. You can ask anything other than that. Thanks. I guess so this is not an issue.

**Comment by davut5** [comment]
I'm actually trying to solve a problem in an application referring to your example. 
i  make a karaoke app like you. my song is playing in Youtube player (UIView). for more info https://github.com/youtube/youtube-ios-player-helper.  i want to capture my voice and youtube videos and record together. But when headphones plugged in, it doesn't work.
